  ##-------download the files-------------------
  if(!file.exists("./data")){dir.create("./data")}
  fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
  download.file(fileUrl,destfile="./data/Dataset.zip")
  unzip(zipfile="./data/Dataset.zip",exdir="./data")

  ##------------read in the training and test data---------------
  subjectTest <- read.table("~/getting-and-cleaning-data-course-project/UCI HAR Dataset/test/subject_test.txt")
  xTest <- read.table("./data/UCI HAR Dataset/test/X_test.txt")
  yTest <- read.table("./data/UCI HAR Dataset/test/y_test.txt")
  subjectTrain <- read.table("./data/UCI HAR Dataset/train/subject_train.txt")
  xTrain <- read.table("./data/UCI HAR Dataset/train/X_train.txt")
  yTrain <- read.table("./data/UCI HAR Dataset/train/y_train.txt")

  ##combine subject Test data into 1 table (subject number, activity type, features)  
  subjectTestComplete <- cbind(subjectTest, yTest, xTest)
  
  ##combine subject Train data into 1 table (subject number, activity type, features)  
  subjectTrainComplete <- cbind(subjectTrain, yTrain, xTrain)

  ##combine Train & Test data into 1 table
  testAndTrainComplete <- rbind(subjectTrainComplete, subjectTestComplete)
  
  ##sort table based on subject#
  orderedTestAndTrainComplete <- testAndTrainComplete[order(testAndTrainComplete[,1]),]
  
  ##----------- make names and labels readable---------------
  ##read feature names to be tidied up and used as column labels, as well as the activity labels
  featureNames <- read.table("./data/UCI HAR Dataset/features.txt")
  featureNames <- featureNames[,2]
  activityNames <- read.table("./data/UCI HAR Dataset/activity_labels.txt")
  activityNames[,2] <- sub("_", ".", tolower(activityNames[,2]))
              
  orderedTestAndTrainComplete[,2] <- replace(orderedTestAndTrainComplete[,2], 1:length(orderedTestAndTrainComplete[,2]), activityNames[orderedTestAndTrainComplete[,2],2])
               
  ## make feature names more readable by swpping abreviations
  ## some charachters are also swapped to make syntactically valid names out of 
  ## character vectors (make.names()) to prepare for further processing
  tidyNames <- sub("^t", "time.domain.signal.of.", featureNames)
  tidyNames <- sub("\\(t", ".time.domain.signal.of.", tidyNames)
  tidyNames <- gsub("\\(|\\)", "", tidyNames)
  tidyNames <- sub("^f", "frequency.domain.signal.of.", tidyNames)
  tidyNames <- sub("Acc", "Acceleration.", tidyNames)
  tidyNames <- sub("Gyro", "Gyroscope", tidyNames)
  tidyNames <- sub("Mag", "Magnitude", tidyNames)
  tidyNames <- sub("(.*)(-std)", "standard.deviation.of.\\1", tidyNames)
  tidyNames <- sub("(.*)(-meanFreq)", "mean.frequency.derived.from.weighted.average.of.\\1", tidyNames)
  tidyNames <- sub("(.*)(-mean)", "mean.of.\\1", tidyNames)
  tidyNames <- sub("angle", "angle.of", tidyNames)
  tidyNames <- sub(",", ".and.", tidyNames)
  tidyNames <- gsub("([[:lower:]])([[:upper:]])", "\\1.\\2", tidyNames)
  tidyNames <- gsub("(.Body)\\1", "\\1", tidyNames)
  tidyNames <- tolower(make.names(tidyNames))
  ## take out extraneous full stops generated by make.names
  tidyNames <- gsub("(.)\\1", "\\1", tidyNames)
  tidyNames <- gsub("(\\.[xyz]$)", "\\1.axis", tidyNames)
  
  ## swap column names
  colnames(orderedTestAndTrainComplete) <- c("subject.number", "activity", tidyNames)
  
  ## select the columns with mean and standard deviation data, including the additional vectors obtained by averaging the signals 
  ## in a signal window sample, used on the angle() variable
  finalMeanandStandardDeviationData <- orderedTestAndTrainComplete[,grep("mean|deviation|subject|activity", colnames(orderedTestAndTrainComplete))]
  
  ## write.csv(finalMeanandStandardDeviationData, "./data/UCI HAR Dataset/mean-and-standard-deviation-data.csv", row.names = FALSE)
  
  ##-------------create the second independent data set with the variable averages-------------
  secondDataSetWithAverages <- aggregate(. ~subject.number + activity, finalMeanandStandardDeviationData, mean)
  secondDataSetWithAverages <- secondDataSetWithAverages[order(secondDataSetWithAverages$subject.number),]
  
  ## write the tidy dataset out to a csv
  write.csv(secondDataSetWithAverages, "./data/UCI HAR Dataset/smartphone-mean-and-standard-deviation-averages.csv", row.names = FALSE)
  
  